### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "firstName": "Anurag",
  "lastName": "Sharma",
  "email": "anurag.user@example.com",
  "password": "User@12345",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### User Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "anurag.user@example.com",
  "password": "User@12345",
  "role":"USER"
}

### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "Vikas",
  "lastName": "Author",
  "email": "vikas.author@example.com",
  "password": "Author@12345",
  "profileImageUrl": "https://example.com/avatars/author.png"
}



### Author Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "vikas.author@example.com",
  "password": "Author@12345",
  "role":"AUTHOR"
}



### Create article (AUTHOR)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author": "698a06fa436ff23f7fc14e79",
  "title":"test2 article",
  "category":"programming",
  "content":"content of test2 article"
}



###Read articles of a author
GET http://localhost:4000/author-api/articles/698965b85a08a6721a29ef61



### Update article (AUTHOR)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"698a06fa436ff23f7fc14e79",
  "articleId":"698a0a0dfc00363cec3dad9a",
  "title":"test2 article updated",
  "category":"programming",
  "content":"content of test2 article updated"
}



### Logout
POST http://localhost:4000/logout

###test
GET http://localhost:4000/test

### blocking user
PUT  http://localhost:4000/admin-api/block/698a06f0436ff23f7fc14e76
Content-Type: application/json

{
  
"email":"anurag.user@example.com",
"password":"User@12345",
"role":"USER",
"isActive":true

}

###unblocking user
PUT  http://localhost:4000/admin-api/unblock/698a06f0436ff23f7fc14e76
Content-Type: application/json

{
  
"email":"anurag.user@example.com",
"password":"User@12345",
"role":"USER",
"isActive":true

}


###changing password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
  "userId":"698a06f0436ff23f7fc14e76",
  "oldPassword": "User@12345",
  "newPassword":"User@123"
}